
import { cmp, File, Content } from '@voxgig/sdkgen'


const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { target, ctx$: { model } } = props

  const Name = model.const.Name

  File({ name: 'ReadmeExamplesTest.' + target.ext }, () => {
    Content(`// ${Name} SDK — documentation csharp-examples PRESENCE + STRUCTURE gate.
//
// GUARANTEE (see ReadmeExamplesTest_csharp.ts for why this is a structure gate
// and not an execute gate): every csharp example in the docs is accounted for.
// This xUnit class is a completeness gate over every ${'```'}csharp fenced code
// block in three documents:
//   - the repository ROOT README.md (two directories above this test file),
//   - the per-language csharp/README.md,
//   - the per-language csharp/REFERENCE.md.
//
// Checks, PER DOCUMENT:
//   1. PRESENCE: the doc exists and holds at least one csharp block.
//   2. STRUCTURE: every csharp block's braces / parens / brackets balance, so a
//      truncated or malformed generated snippet fails loudly.
//
// GENERATED by @voxgig/sdkgen — do not edit by hand.

using System.Runtime.CompilerServices;

using Xunit;

namespace ${Name}Sdk.Test;

public class ReadmeExamplesTest
{
    // The .cs source directory, resolved at compile time — robust to the test
    // runner's working directory.
    private static string SourceDir([CallerFilePath] string path = "")
        => System.IO.Path.GetDirectoryName(path)!;

    private static string CsharpRoot()
        => System.IO.Path.GetFullPath(System.IO.Path.Combine(SourceDir(), ".."));

    private static (string label, string path)[] Docs()
    {
        var root = CsharpRoot();
        return new[]
        {
            ("root README", System.IO.Path.GetFullPath(
                System.IO.Path.Combine(root, "..", "README.md"))),
            ("csharp README.md", System.IO.Path.Combine(root, "README.md")),
            ("csharp REFERENCE.md", System.IO.Path.Combine(root, "REFERENCE.md")),
        };
    }

    // Extract every csharp fenced block. Split on the triple-backtick fence:
    // odd-indexed segments are the inside of a fenced block (info string on the
    // first line, then the code). Only blocks whose info string is exactly
    // "csharp" are returned.
    private static List<string> CsharpBlocks(string text)
    {
        var fence = new string((char)96, 3);
        var parts = text.Split(fence);
        var blocks = new List<string>();
        for (var i = 1; i < parts.Length; i += 2)
        {
            var seg = parts[i];
            var nl = seg.IndexOf('\\n');
            var info = (nl < 0 ? seg : seg.Substring(0, nl)).Trim();
            if (info == "csharp")
            {
                blocks.Add(nl < 0 ? "" : seg.Substring(nl + 1));
            }
        }
        return blocks;
    }

    private static string ReadDoc(string path, string label)
    {
        Assert.True(System.IO.File.Exists(path), label + " not found: " + path);
        return System.IO.File.ReadAllText(path);
    }

    // True when every open/close delimiter balances (ignores the subtlety of
    // delimiters inside string literals — a generated snippet never nests an
    // unbalanced delimiter in a string, and this catches truncation).
    private static bool Balanced(string block)
    {
        var stack = new Stack<char>();
        var pairs = new Dictionary<char, char> { ['('] = ')', ['['] = ']', ['{'] = '}' };
        var closers = new HashSet<char> { ')', ']', '}' };
        foreach (var ch in block)
        {
            if (pairs.ContainsKey(ch))
            {
                stack.Push(pairs[ch]);
            }
            else if (closers.Contains(ch))
            {
                if (stack.Count == 0 || stack.Pop() != ch)
                {
                    return false;
                }
            }
        }
        return stack.Count == 0;
    }

    [Fact]
    public void RootReadmeHasCsharpBlocks()
    {
        var doc = Docs()[0];
        var blocks = CsharpBlocks(ReadDoc(doc.path, doc.label));
        Assert.True(blocks.Count > 0,
            "expected at least one csharp block in " + doc.label);
    }

    [Fact]
    public void LocalReadmeHasCsharpBlocks()
    {
        var doc = Docs()[1];
        var blocks = CsharpBlocks(ReadDoc(doc.path, doc.label));
        Assert.True(blocks.Count > 0,
            "expected at least one csharp block in " + doc.label);
    }

    [Fact]
    public void ReferenceHasCsharpBlocks()
    {
        var doc = Docs()[2];
        var blocks = CsharpBlocks(ReadDoc(doc.path, doc.label));
        Assert.True(blocks.Count > 0,
            "expected at least one csharp block in " + doc.label);
    }

    [Fact]
    public void AllCsharpBlocksAreStructurallyBalanced()
    {
        var failures = new List<string>();
        var fence = new string((char)96, 3);
        foreach (var doc in Docs())
        {
            if (!System.IO.File.Exists(doc.path))
            {
                continue;
            }
            var text = System.IO.File.ReadAllText(doc.path);
            // A well-formed document has an EVEN number of triple-backtick fence
            // markers — every block that opens also closes. An odd count means a
            // fence was opened but never closed at end-of-document; because block
            // extraction keys off fence parity, such an unterminated csharp block
            // can silently vanish instead of being checked. Fail loudly.
            if ((text.Split(fence).Length - 1) % 2 != 0)
            {
                failures.Add(doc.label +
                    " has an unclosed code fence (odd number of triple-backtick markers)");
            }
            var blocks = CsharpBlocks(text);
            var balanced = 0;
            for (var i = 0; i < blocks.Count; i++)
            {
                if (Balanced(blocks[i]))
                {
                    balanced++;
                }
                else
                {
                    failures.Add(doc.label + " csharp block #" + i +
                        " has unbalanced delimiters:\\n\\n" + blocks[i]);
                }
            }
            System.Console.WriteLine(
                "[readme-examples] " + doc.label + " csharp blocks: total=" +
                blocks.Count + " balanced=" + balanced);
        }
        Assert.True(failures.Count == 0,
            string.Join("\\n\\n", failures));
    }
}
`)
  })
})


export {
  ReadmeExamplesTest
}
